### ISSUE TITLE
How the High-order works ?

### ISSUE THREAD

**Issue by bratao** [hiroshi-manabe/CRFSegmenter#1]
First of all, congratulations on releasing this awesome codebase. It is very well written, and my preliminary tests on POS showed that it is very performant.

But reading the code I did not understand how the high-order CRF works. What is the order ? How do you set it ? It uses a fancy algorithm ?

Could you also explain that the parameter "--wordl  <number>\tMaximum label length of words." means ? 
From a quick glance, I can see that this insert many new features. Is it that controls the order of the CRF ?

Many thanks again!!!

**Comment by hiroshi-manabe** [comment]
Thank you for using our software!

> What is the order ?

In the conventional CRFs, the order is usually 1 -- i.e. the feature functions are in the form of f(i, Y<sub>i-1</sub>, Y<sub>i</sub>, X).  They are called _first_-order CRFs, because they assume first-order Markov process, but I personally prefer calling them _2_-label CRFs.

In our software, we use the high-order CRFs, which is a simple extension of first-order (2-label) CRFs. The idea is just using more than 2 labels. You can find a previous work [here](http://papers.nips.cc/paper/3815-conditional-random-fields-with-high-order-features-for-sequence-labeling.pdf).

In the high-order CRFs, the computational complexity goes up very quickly with a simple algorithm and using an efficient algorithm is the key.

> It uses a fancy algorithm ?

Yes, it uses an algorithm conceived by me, and I hope it's a fancy one.

Unfortunately, I published it only in my master's thesis and in a Japanese paper, so there is no published English version available. I tried to translate it in English but it is still underway and not even proofread. You can find it [here](http://vocrf.net/docs/thesis_en.pdf) and the original thesis [here](http://vocrf.net/docs_ja/thesis.pdf). (I called them _variable-order_ CRFs there. Now I prefer calling them _high-order_, but they are the same thing.)

> Is it that controls the order of the CRF ?

Yes, as you have correctly guessed, it is "--wordl" parameter that controls the order of the CRF.

"--wordl" parameter defaults to 4 (which translates to _third_-order), which means it generates features with up to 4 labels.

But, unfortunately, things are not as simple as that -- "--wordn" and "--wordw" parameters also come into play.

"--wordw" is the maximum word window size and "--wordn" is the ngram length -- these parameters are like the ones in [kytea](http://www.phontron.com/kytea/method.html), but a little bit different. Let me explain with an example.

Let's assume the sentence is "Alice was beginning to get very tired of sitting by her sister on the bank" and the word we are trying to tag is "get". "--wordw" determines the range from which the software generates the feature functions. If "--wordw" is 2, the range is from "beggining" (current position - 2) ... "very" (current position + 2 - 1). (I'm not sure why I decided to -1, but it is so for now.) "--wordn" determines the maximum word cluster length: For example, if "--wordw" is 2 and "--wordn" is also 2, the generated word clusters are "W-2/beggining_to", "W-1/to", "W-1/to_get", "W+0/get" and "W+0/get_very". Note that "W-2/beggining" and "W+1/very" are not generated. The rationale is that a non-adjacent word is seldom useful when inferring the label. (I noticed it is not the case with "W+1/very", which is an adjacent word of "get". I will try fixing it along with the range of "--wordw".)

Feature functions are generated from these word clusters and labels. The maximum length of the label sequence is limited by "--wordl" parameter, but also by the word cluster with which the feature function is generated. In the above example, for the clusters "W-1/to" and "W-1/to_get", only feature functions up to 3 labels (i.e. second-order) are generated; this is because features with more than 4 labels include labels for "was", which is not included in and not adjacent to the word clusters. (Sorry that my explanation is somewhat cluttered ...) So in this case, the only 4-label (i.e. third-order) feature function generated here is the one with "W-2/beggining_to".

If you have more questions, don't hesitate to ask me. Answering questions helps me organize the things!

One question from me: How did you come to know this software? It was the first day of publishing when you opened this issue. Just being curious.

**Comment by bratao** [comment]
@hiroshi-manabe , thank you so much for the very detailed explanation. It helped a lot!

I understood everything until the explanation of "wordl". At this part I got confused. 
I understood that in "WordFeatureGenerator::generateFeatureTemplates" it generate those features with "W-Window" prefix. It creates FeatureTemplate objects with that labelLength. 
It is used later in the function "DataSequence::accumulateFeatureData".

Can you explain "DataSequence::accumulateFeatureData" ? I guess that with this I will understood the "wordl" 

I discovered this project because of my master project. I constantly searching Github  for sequential labelling projects. I´m working on transforming semi structured text  to a structured format. I modeled my problem as a Sequential Tagging.
For example, the text:

> Actor: John Snow (02/02/1980) , Actress: Jane Doe (03/03/1981)

Became:

```
{
"persons": [
    { "type": "Actor",
    "name": "John Snow",
    "birthday": "02/02/1980"},

    { "type": "Actress",
    "name": "Jane Doe",
    "birthday": "03/03/1981"}, 
 ]
}
```

So far, your project is on with the best performance so far. I got a higher accuracy than Crfsuite, when I use just the token. Congratulations !
However I need to use extra handcrafted features, that I cannot use with CRFSegmenter now. I plan to implement this at CRFSegmenter. Can you advice me? 
My plan is to use the input as :

`token1;feature1;feature2/label1 token2;feature3;feature2/label2`

And at "WordFeatureGenerator::generateFeatureTemplates" split at ';' and add those as new features at "featureTemplateListList"

Do you think this can work ? I will create a fork and try to do something. 

Thank you again for this awesome project and help !

**Comment by hiroshi-manabe** [comment]
> Can you explain "DataSequence::accumulateFeatureData" ? I guess that with this I will understood the "wordl"

I'm not sure if explaining "DataSequence::accumulateFeatureData" will help you understand "wordl", but I'll give it a try:

"DataSequence::accumulateFeatureData" is a method which counts "empirical sum of the feature f<sub>i</sub> in the observed data" ([Nan 2009](http://papers.nips.cc/paper/3815-conditional-random-fields-with-high-order-features-for-sequence-labeling.pdf)). 

Maybe explaining `Feature` and `FeatureTemplate` will help you.

A `Feature` is a feature function in the form of f(**x**, **y**, t) (**x** being the observations and **y** being the labels). Each feature function has a `LabelSequence` (`seq`) as its member variable and returns 1 if `y[t-f.seq.getLength()+1..t]` matches `seq` and **x** satisfies its condition. But a `Feature` does not judge if **x** satisfies its condition; the judgment is done when generating `FeatureTemplate`.

A `FeatureTemplate` is a `Feature` without a `LabelSequence`. A `FeatureTemplate` only has the length of the `LabelSequence` and it can be used to generate `Feature`s combined with some label sequence.

`FeatureTemplate`s are generated by `FeatureTemplateGenerator`s. The reason why we generate `FeatureTemplate`s, not `Feature`s, is that we are usually interested in the order (or label length) of the feature functions and not in the concrete labels. A `FeatureTemplate` also has a `obs` variable, which is an identifier.

Let's take an example from the [documentation of CRFsuite](http://www.chokkan.org/software/crfsuite/manual.html). In this example, the `attributes` like "w[0]=An" and "w[1]=A.P." correspond to our `obs` variable and can be seen as _feature templates_.

In this example, there is no _label length_ associated with these _feature templates_; that's because the feature functions associated with attributes are always zero-order (they have only 1 label). But they are essentially _feature templates_ in the sense they are combined with labels and generate feature functions: For "w[0]=An", a feature function with the label B-NP will be generated.

In CRFSegmenter, though, feature templates can have more than 1 label, so we have to specify the length of the label sequence associated with them. Let's take the "w[-1]=An" attribute in the second line as an example. If we are to generate a feature template with 1 label, then it will generate a feature function with the label "I-NP" (the same as in CRFsuite); if we are to generate a feature template with 2 labels, then it will generate a feature function with the labels B-NP:I-NP.

The "--wordl" parameter is what limits the label length of the feature functions that `Tagger` generates. The `Tagger` program corresponds to the sample scripts (like `ner.py` and `pos.py`) in CRFsuite -- they generate feature templates.

I am considering making `Tagger` (and `Segmenter`) more independent, like the sample scripts in CRFsuite... they are too intertwined with HighOrderCRF now.

> So far, your project is on with the best performance so far. I got a higher accuracy than Crfsuite, when I use just the token. Congratulations !

Thank you, I'm very glad to know that!

> However I need to use extra handcrafted features, that I cannot use with CRFSegmenter now. I plan to implement this at CRFSegmenter.

You will need to derive a subclass from `FeatureTemplateGenerator` and implement your own `generateFeatureTemplates`, then add your class to `AggregatedFeatureTemplateGenerator` using `addFeatureTemplateGenerator`.

> Do you think this can work ? I will create a fork and try to do something.

I will take a look when you create a fork. Sorry that I haven't written LICENSE yet, but I will write it as soon as possible (it will be MIT license). Good luck!

**Comment by bratao** [comment]
Thank you so much @hiroshi-manabe , I understood everything now. 
I will try to implement the "read extra features from input" in a fork and will keep you informed about my results!
